# Problem 2: Even Fibonacci numbers
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

fibonacci_list = []
def fibonacci(a, b, number):
    for i in range(number):
            if b > number:
                break
            if b % 2 == 0:
                fibonacci_list.append(b)
            a, b = b, a + b


numbers_until = 4000000
fibonacci(0, 1, number=numbers_until)
# print(fibonacci_list)
sum = sum(fibonacci_list)
print(sum)

# Output:
# 4613732